export const FETCH_CARDS_START = 'FETCH_CARDS_START';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';
export const SET_NEXT_CARD = 'SET_NEXT_CARD';
export const SET_PREVIOUS_CARD = 'SET_NEXT_CARD';
export const SET_LOADING = 'SET_LOADING'


export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';


export const LIKE_CARD_START = 'LIKE_CARD_START';
export const LIKE_CARD_SUCCESS = 'LIKE_CARD_SUCCESS';
export const LIKE_CARD_FAILED = 'LIKE_CARD_FAILED';



export const FETCH_FAVORITE_USERIDS_START = 'FETCH_FAVORITE_USERIDS_START';
export const FETCH_FAVORITE_USERIDS_SUCCESS = 'FETCH_FAVORITE_USERIDS_SUCCESS';
export const FETCH_FAVORITE_USERIDS_FAILED = 'FETCH_FAVORITE_USERIDS_FAILED';

export const FETCH_FAVORITE_CARDS_START = 'FETCH_FAVORITE_CARDS_START';
export const FETCH_FAVORITE_CARDS_SUCCESS = 'FETCH_FAVORITE_CARDS_SUCCESS';
export const FETCH_FAVORITE_CARDS_FAILED = 'FETCH_FAVORITE_CARDS_FAILED';


export const CLEAR_FAVORITE_USER_LIKES = 'CLEAR_FAVORITE_USER_LIKES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';