export const FETCH_CARDS_START = 'FETCH_CARDS_START';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';


export const SET_NEXT_CARD = 'SET_NEXT_CARD';
export const SET_PREVIOUS_CARD = 'SET_NEXT_CARD';

export const SET_LOADING = 'SET_LOADING'